import type { Metadata } from "next";
import { Gloock } from "next/font/google"; 
import { Poppins } from "next/font/google"; 
import "./globals.css";

const gloock = Gloock({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-gloock',
});
const poppins = Poppins({
    weight: '400',
    subsets: ['latin'],
    variable: '--font-poppins',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${gloock.variable} ${poppins.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}